### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by SrevSA** [Basicconstruction/turboUI#1]
![изображение_2023-12-05_051752243](https://github.com/Basicconstruction/turboUI/assets/37821167/0946ba67-4695-4041-891a-1719cdff670f)

**Comment by Basicconstruction** [comment]
由于python的编译产品没有添加到最新的包中，下载最新的1.01或者1.00即可。 git有两套，默认为gitee，有时候推送github不及时，尤其设计到turbo-proxy

**Comment by Basicconstruction** [comment]
昨天晚上更新了最新的编译包

**Comment by Basicconstruction** [comment]
Since the python compilation product has not been added to the latest package (the 1.00 version release package from 12.3 to 12.4), the compilation package was updated on the night of 12.4, just download the latest 1.01 or 1.00.
